In [52]:
!pip install numpy

In [53]:
import numpy as np

In [54]:
arr1=np.array([1,2,3,4,5,6,7])

In [55]:
print("numpy array:",arr1)

numpy array: [1 2 3 4 5 6 7]


In [56]:
arr2 =np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]


In [57]:
arr3 =np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [58]:
print(arr3.ndim)

3


In [62]:
print(arr1[-6:-2])

[2 3 4 5]


In [69]:
print(arr2[0:2,2])

[3 6]


In [70]:
arr9=np.array([1,2,3,4],dtype='S')
print(arr9)
print(arr9.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [74]:
arr8=np.array([1.1,2.1,3.1])
newarr=arr8.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32
